### ISSUE TITLE
Skips a line and makes a line at the end??

### ISSUE THREAD

**Issue by skybldev** [Osterjour/line-by-line#26]
This is some weird, weird stuff going on. I'm too tired to explain it right now, that's why I started [**this repo**](https://github.com/Luxray5474/linebylinetest) to show the bare basics of what the problem I'm facing is. 

The expected outcome of running test.js is that in `output.txt` (it will create it when you run the script, don't worry) there will be 17,885 lines -- two more than the 17,883 of `Log.txt`, and the cause of that are two empty lines on `:17150` and `:17885`. Those are obviously not supposed to be there.

Node version: 8.11.2
line-by-line version: 0.1.6

**Comment by hugoamaro** [comment]
I found this issue too, but by performing a different task. When reading a large file where each line is a JSON object, the parser complained with a parse error due to receiving an empty line.
We are still analyzing the issue but apparently the line wasn't skipped, nor reordered, it simply fired a empty _online_ event in between lines.
